#!/usr/bin/env ruby

require 'rest-client'
require 'csv'
require 'cgi'
require 'nokogiri'

def simplify(string)
  string.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
end

imdb_rating, email, password = ARGV

ROOT="http://www.senscritique.com"

resp = RestClient.post "#{ROOT}/auth/login.json", {email: email, pass: password}
cookies = resp.cookies

RestClient.get imdb_rating do |csv_body|
  CSV.parse(csv_body)[1..-1].each do |row|
    title, author, year, rating = row[5], row[7], row[11], row[8]
    query = "#{title} #{author} #{year}"
    url = "#{ROOT}/recherche?query=#{CGI.escape(query)}&filter=movies"

    puts "#{title} => #{rating} (#{url})"

    RestClient.get url do |result|
      movie_node = Nokogiri::HTML(result).css(".elsea-li").find do |li|
        author_node = li.css(".elprlc-a")
        author_node ? author_node.attr('title').to_s == author : false
      end

      if movie_node
        RestClient.post "#{ROOT}/collections/rate/#{movie_node['data-sc-product-id']}.json", {rating: rating}, {cookies: cookies}
      end
    end
    sleep 5
  end
end
