#!/usr/bin/env ruby

require 'rest-client'
require 'csv'
require 'cgi'
require 'nokogiri'

imdb_rating, email, password = ARGV

ROOT="http://www.senscritique.com"

resp = RestClient.post "#{ROOT}/auth/login.json", {email: email, pass: password}
cookies = resp.cookies

RestClient.get imdb_rating do |csv_body|
  CSV.parse(csv_body)[1..-1].each do |row|
    query = "#{row[5]} #{row[7]} #{row[11]}"
    rating = row[8]
    url = "#{ROOT}/recherche?query=#{CGI.escape(query)}&filter=movies"

    puts "Rate #{row[5]} => #{row[8]} (#{url})"

    RestClient.get url do |result|
      li = Nokogiri::HTML(result).css(".elsea-li").first
      id = li['data-sc-product-id']
      RestClient.post "#{ROOT}/collections/rate/#{id}.json", {rating: rating}, {cookies: cookies}
    end
    sleep 5
  end
end
